services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: 
        [
          "CMD-SHELL",
          "curl -s http://es:9200 >/dev/null || exit 1",
        ]
      interval: 20s
      timeout: 10s
      retries: 50
  index:
    depends_on:
      es:
        condition: service_healthy
    build: ./
    command: python app/indexer.py
  app:
    depends_on:
      es:
        condition: service_healthy
    build: ./
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000

volumes:
  esdata:
